### ISSUE TITLE
splitChunks疑问

### ISSUE THREAD

**Issue by bowencool** [luckyyyyy/vue-templates-typescipt#1]
### 问题：app里同时包含了entry和vendor。
![image](https://user-images.githubusercontent.com/20217146/57746366-7d29a800-7703-11e9-8197-c6da31c1c96d.png)

### 我尝试了下把他们分开，没有成功。结果就是两种：

1.和上图一样
2.vue-family也被打进vendor了
![image](https://user-images.githubusercontent.com/20217146/57746855-9f242a00-7705-11e9-9704-9c123c3cb650.png)

所以，这个想法能实现吗，大佬你能不能试一下？

**Comment by luckyyyyy** [comment]
![image](https://user-images.githubusercontent.com/9210430/57827868-b46b8800-77db-11e9-908f-11653e22abe8.png)


?

**Comment by luckyyyyy** [comment]
你是想要这样吗
